-- PANTAINI CAFÉ POS : Supabase Database + Auth + RLS
-- 1) วางทั้งหมดนี้ใน Supabase > SQL Editor > New query แล้ว Run

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'staff' check (role in ('admin','staff')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(category,name)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no bigint generated by default as identity unique,
  cashier_id uuid not null references public.profiles(id),
  payment_method text not null check (payment_method in ('cash','qr')),
  total numeric(10,2) not null check (total >= 0),
  received numeric(10,2),
  change_amount numeric(10,2) not null default 0,
  status text not null default 'paid' check (status in ('paid','void')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10,2) not null,
  quantity integer not null check (quantity > 0),
  line_total numeric(10,2) generated always as (unit_price * quantity) stored
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_cashier_idx on public.orders(cashier_id);
create index if not exists order_items_order_idx on public.order_items(order_id);

-- สร้าง profile อัตโนมัติหลังสมัคร/สร้าง user ใน Authentication
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)), 'staff')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- helper เช็ค admin
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- ล้าง policy เก่า (ปลอดภัยสำหรับรันใหม่)
drop policy if exists "profiles read own or admin" on public.profiles;
drop policy if exists "profiles admin manage" on public.profiles;
drop policy if exists "products authenticated read" on public.products;
drop policy if exists "products admin manage" on public.products;
drop policy if exists "orders read own or admin" on public.orders;
drop policy if exists "orders insert own" on public.orders;
drop policy if exists "orders admin update" on public.orders;
drop policy if exists "items read own order or admin" on public.order_items;
drop policy if exists "items insert own order" on public.order_items;

create policy "profiles read own or admin" on public.profiles
for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles admin manage" on public.profiles
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "products authenticated read" on public.products
for select to authenticated using (true);
create policy "products admin manage" on public.products
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "orders read own or admin" on public.orders
for select to authenticated using (cashier_id = auth.uid() or public.is_admin());
create policy "orders insert own" on public.orders
for insert to authenticated with check (cashier_id = auth.uid());
create policy "orders admin update" on public.orders
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "items read own order or admin" on public.order_items
for select to authenticated using (
  public.is_admin() or exists(select 1 from public.orders o where o.id = order_id and o.cashier_id = auth.uid())
);
create policy "items insert own order" on public.order_items
for insert to authenticated with check (
  exists(select 1 from public.orders o where o.id = order_id and o.cashier_id = auth.uid())
);

-- เมนูเริ่มต้น
insert into public.products(category,name,price) values
('COFFEE','อเมริกาโน่',40),('COFFEE','เอสเปรสโซ่',45),('COFFEE','ลาเต้',45),('COFFEE','คาปูชิโน่',50),('COFFEE','มัคคิอาโต้',50),('COFFEE','อเมริกาโน่บราวน์ชูการ์',50),('COFFEE','อเมริกาโน่ส้ม',50),('COFFEE','อเมริกาโน่มะพร้าว',50),('COFFEE','อเมริกาโน่สตรอเบอร์รี่',50),('COFFEE','อเมริกาโน่เงาะ',50),
('MATCHA','เพียวมัทฉะ',40),('MATCHA','มัทฉะลาเต้',45),('MATCHA','มัทฉะมะพร้าว',50),('MATCHA','มัทฉะสตรอเบอร์รี่',45),('MATCHA','มัทฉะสตรอว์เบอร์รี่',50),
('TEA','ชาดำ',30),('TEA','ชามะนาว',35),('TEA','ชาเขียว',35),('TEA','ชาเขียวสตรอเบอร์รี่',45),('TEA','ชาเย็น',35),('TEA','ชาพีช',40),('TEA','โกโก้สตรอเบอร์รี่',45),('TEA','ชาเงาะ',45),
('MILK','ชูกับบา',35),('MILK','โกโก้',35),('MILK','นมสตรอเบอร์รี่',40),('MILK','นมคาราเมล',40),('MILK','นมบราวน์ชูการ์',40),('MILK','นมแอปเปิ้ล',40),('MILK','โกโก้มินต์',40),('MILK','โกโก้คาราเมล',40),('MILK','โกโก้สตรอเบอร์รี่',45),
('SODA','แอปเปิ้ล',35),('SODA','พีช',35),('SODA','สตรอเบอร์รี่',35),('SODA','บลูเลมอน',35),('SODA','น้ำผึ้งมะนาว',35),
('APPETIZERS','เฟรนช์ฟรายส์',29),('APPETIZERS','ชีสบอลทอด',29)
on conflict (category,name) do nothing;

-- หลังสร้าง user เจ้าของร้านคนแรกแล้ว ให้เอา email ไปเปลี่ยนเป็น admin:
-- update public.profiles p set role='admin' from auth.users u where p.id=u.id and u.email='YOUR_ADMIN_EMAIL';

-- เปิด Realtime สำหรับหลายเครื่อง
alter publication supabase_realtime add table public.products;
alter publication supabase_realtime add table public.orders;
